#!/usr/bin/env bash

VALHALLA_DATA_DIR=${VALHALLA_DATA_DIR:-./valhalla-data}

S3_ENDPOINT="${S3_ENDPOINT:-s3.localhost}"
S3_PORT="${S3_PORT:-3000}"
S3_SCHEME="${S3_SCHEME:-http}"
S3_ACCESS_KEY="${S3_ACCESS_KEY:-root}"
S3_SECRET_KEY="${S3_SECRET_KEY:-password}"
S3_BUCKET="${S3_BUCKET:-valhalla-data}"

DATE=$(date +%Y.%m.%d)
VALHALLA_TILE_ARCHIVE_PREFIX=${VALHALLA_TILE_ARCHIVE_PREFIX:-valhalla-tiles}
VALHALLA_TILE_ARCHIVE=${VALHALLA_TILE_ARCHIVE:-$VALHALLA_TILE_ARCHIVE_PREFIX-$DATE.tar.gz}

echo "DATA: $DATE"
echo "VALHALLA_TILE_ARCHIVE_PREFIX: $VALHALLA_TILE_ARCHIVE_PREFIX"
echo "VALHALLA_TILE_ARCHIVE: $VALHALLA_TILE_ARCHIVE"

mc alias set remote "$S3_SCHEME://$S3_HOST:$S3_PORT" "$S3_ACCESS_KEY" "$S3_SECRET_KEY"
mc cp remote/$S3_BUCKET/$VALHALLA_TILE_ARCHIVE /tmp/$VALHALLA_TILE_ARCHIVE
cd /tmp
tar xzf $VALHALLA_TILE_ARCHIVE 
cp -r $VALHALLA_DATA_DIR /app

exec "$@"
